name: TEST CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build-connect:
    runs-on: ubuntu-latest
    services:
      databend:
        image: datafuselabs/databend
        env:
          QUERY_DEFAULT_USER: databend
          QUERY_DEFAULT_PASSWORD: databend
          MINIO_ENABLED: true
        # options: >-
        #   --health-cmd "curl -fs http://localhost:8000/v1/health || exit 1"
        #   --health-interval 10s
        #   --health-timeout 5s
        #   --health-retries 5
        ports:
          - 8000:8000
          - 9000:9000
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare java
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.8.2

      - name: Maven Build
        run:  mvn -Passembly -Dmaven.test.skip package

      - name: Databend Kafka Integration test
        run:  mvn test -D test=DatabendSinkIT