name: TEST CI

on:
  pull_request:
    branches: [main]

jobs:
  build-connect:
    runs-on: [self-hosted, X64, Linux, 8c16g]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare java
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.8.2

      - name: Maven Build
        run:  mvn -passembly -Dmaven.test.skip package

      - name: Databend Kafka Integration test
        run:  mvn test -D test=DatabendSinkIT